# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.0.1
     hooks:
        - id: check-ast
        - id: check-json
        - id: check-yaml
        - id: check-case-conflict
        - id: detect-private-key
        - id: detect-aws-credentials
          args: [--allow-missing-credentials]
        - id: debug-statements
        - id: check-docstring-first
        - id: check-added-large-files
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: mixed-line-ending
# imports management
   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: v0.812
     hooks:
        - id: mypy
          args: [--ignore-missing-imports]

   - repo: https://github.com/pre-commit/mirrors-isort
     rev: v5.8.0
     hooks:
        - id: isort
# python upgrade
   - repo: https://github.com/asottile/pyupgrade
     rev: v2.18.1
     hooks:
        - id: pyupgrade
          args: [--py36-plus]
